travis:
  secure:
    BINSTAR_TOKEN: Qcw5EHDWbJprDsH6e3bvaqT/dk/+nYFa7p9RIJvMKk/8oYk7kNCjRcki0AUgE9eDZFa5HPa8D4o4tShcrugGHpW0oKp2vwx2flhzmKXlXAikEWnEy80fMtNajyaxOAD080vIaUR+lYXKjNmY44O9o05T5ggZJzALFz2aEA73D/5ZNxN4EQMq5nxfWysirrPSGLcDiUtN0vHPBNkH0YOW9MYlg3YGhPmiXjihCCuAsTBS8X0MdCDhKbR6UK5Ju9LRrLurXe/mecCwFIcrhU9wdWIJsPgIuFzw7F6wGCDoF477aWYbj9IeXqy8y+dy3NTr1b5tcxM/p7O3C5vln4p+FD0Kv5wh+A4TU2lEPaugDgrmTovT3oGCDd4bkgRNjIz1IU/vtKzlwmdEbFZSdVUQWNcJUv3TCsWfGK/V7kznwRkd7QEc6S+TT4/Zq4mPRThWxiQSxGFU+bpYgGuJCp1BvWhwncFVvroslHB4zcfL9oIFBgEdV0PgLmuLVqlefgqcutE+yhEbG5atRSYr48u2cikkFR7x9GMGDMA/9MQ2XTgSQP5l3OEgZ/GXkVEoGcV4kIlrqUjX+AYf5cmhKllZCr0wRmaqb+rZICbSAr/hSiR0kSh+lnd51SRff7w9syAYpBXneLMRimVVwJuf4cC6Ni4+eTtmf+s+a47fhWI8bGA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
