travis:
  secure:
    BINSTAR_TOKEN: Bsy2IWnMOgsAsYgzAgmvIOZvesOVzvxp5aTzdHBq3Ommx672RsUhEuW7m9XlQb9GpYJkAXxPBpNaEV2pndX9UwD6XKMcJt9JGUX9Jek/TpoZtsluPi33Cu7dIjuaCW3j3iKpXO4jhDJefDeYLMvXOZL8UHAQ0KbebV2ZAGA94FiRGY1FaMrV8XfZJk9uvSS9yoYPUsQdg3bhd7+AhLmJ7Jmw7h28OQh9S/y8h5V36hF8D2PWfZsqCL2EJZJIuVEp7AWnb3p/nJk66o5BkNlmhzBEFa+cJj4U6twibKLnb676M20dZ0kByi+9+QttwZWD3Lf/OXU6FJNvaCKwVcSN/XUGnIugw7aCEpClBuVU9Jrbn2dx1pLXOS0yF0EIBKqeM5/J1aGMi8CCvJoVNeAGWhNf8J2ce9LxDrJv9rnJ9fdLaD9KYBxBKNiam1Zw3tIipl9Q+xt1i90g1Ptsj5cYVDuJGqlwL6iKCzXZXvleU4HpmT7l3CC0PP2qJSYEdB7vsJuuD/MmQ2DvV+fYjhkJthPYveo0VxC+14ksmGv2WLA9+ynY5OMJNCLFCR9vIZZ4BbdK+O20lBaQxBEgqCb3ABiGyDS62lws9yHPMp8ujxZ7uA6KqF1KX1Zg2/vgsXncZf6aFV57g0YdBR6I0RhYjHQhGwrEMoN4I9wWeqq37tc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
